CC = gcc
CFLAGS = -g -Wall
LDFLAGS = -lm

PROGRAMS = scanf gets scanf-alternativo fgets scanf-alternativoN \
           puts funcoes ordena tamanho copia copia-completo


all: $(PROGRAMS)

clean:
	rm -f *.o *~ $(PROGRAMS)
